### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by Ceilopty** [kansaer/dandanplay-apiNode#1]
大佬的python自建版代码第76行对上安卓概念版好像有点小意外，subgroup和type为缺省的时候传过去的参数是空串而不是None，会被Optional打回来...

**Comment by Ceilopty** [comment]
在别处看到大佬早就给解决方案了。。。

**Comment by AOALI123** [comment]
解决方案在哪里 求教 我也422

**Comment by Ceilopty** [comment]
哇塞太久了不记得了都。。而且现在版本好像跟我当时看见的不一样了。。Optional [str]都删了？

**Comment by Ceilopty** [comment]
嗯，如果是2021.1.11的代码大概率会422，把字幕组和分类选上后应该也能用，不过我猜2021.4.14那版已经修正了。但那版run_host 和run_port莫名其妙消失了，可能依旧422，而且怎么点都422。也不知道你用的哪一版

**Comment by AOALI123** [comment]
我是1月那版 21年1月份架好以后我就再没动过 现在出差 没有电脑用 无聊的很 手机下了个概念版 结果422了
